---
abstract: 'Pure-Perl non-blocking I/O MongoDB driver'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132620'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mango
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mojolicious: 4.0
  perl: 5.010001
resources:
  MailingList: http://groups.google.com/group/mojolicious
  bugtracker: http://github.com/kraih/mango/issues
  homepage: http://mojolicio.us
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/kraih/mango
version: 0.13
