--- 
abstract: An ecommerce solution using Catalyst, Handel and DBIx::Class
author: Christopher H. Laco
build_requires: 
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Mango
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI::FormBuilder: 0
  Catalyst: 5.7007
  Catalyst::Action::REST: 0.40
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Authentication: 0.09999
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Class::Accessor::Grouped: 0.03
  Class::Inspector: 0
  Clone: 0
  DBIx::Class: 0.07999_02
  DateTime: 0
  Error: 0
  FormValidator::Simple: 0.17
  Handel: 0.99_18
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  Locale::Maketext: 0
  MIME::Types: 0
  Path::Class: 0
  Scalar::Util: 0
  XML::Atom: 0.25
  XML::Feed: 0.12
  XML::RSS: 1.22
  YAML: 0
  perl: 5.8.1
tests: t/*.t t/*/*.t
version: 0.01000_04
