# $Id: /local/Mango/trunk/share/forms/admin/roles/edit.yml 1828 2007-08-11T00:17:05.755369Z claco  $
---
id: roles_edit
name: roles_edit
method: POST
javascript: 0
stylesheet: 1
sticky: 1
submit: LABEL_UPDATE
fields:
  - id:
      type: hidden
      force: 1
      constraints:
        - NOT_BLANK
        - UINT
  - name:
      type: text
      size: 25
      disabled: 1
      force: 1
      maxlength: 25
      constraints:
        - NOT_BLANK
        - LENGTH, 1, 25
  - description:
      type: text
      size: 50
      maxlength: 100
      constraints:
        - NOT_BLANK
        - LENGTH, 1, 100
  - created:
      size: 20
      disabled: 1
